[tools]
rojo = "rojo-rbx/rojo@7.6.1"
wally = "UpliftGames/wally@0.3.2"
selene = "Kampfkarren/selene@0.30.1"
stylua = "JohnnyMorganz/stylua@2.4.1"
zap = "red-blox/zap@0.6.28"
blink = "1Axen/blink@0.18.8"
