[package]
name = "kurang-dana/satset"
description = "High-performance, buffer-backed hybrid networking for Roblox with zero-allocation delta synchronization."
version = "0.1.0"
license = "MIT"
authors = ["Iqbal F"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [
	".gitattributes",
	".gitignore",
	"default.project.json",
	"package.json",
	"stylua.toml",
	"selene.toml",
]

[dependencies]
ByteNet = "ffrostflame/bytenet@0.4.6"
BridgeNet2 = "ffrostflame/bridgenet2@1.0.0"
Warp = "imezx/warp@1.0.0"