[package]
name = "bookek/satset"
description = "High-performance, buffer-backed hybrid networking for Roblox with zero-allocation delta synchronization."
version = "0.1.3"
license = "MIT"
authors = ["Iqbal F"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [
	"**/*.rbxl",
	"**/*.rbxlx",
	"**/*.rbxm",
	".gitattributes",
	".gitignore",
	".github",
	"references",
	"benchmark",
	"docs",
	"tests",
	"default.project.json",
	"build.project.json",
	"package.json",
	"stylua.toml",
	"selene.toml",
	"rokit.toml",
	"wally.lock",
	"CONTRIBUTING.md",
]

[dev-dependencies]
ByteNet = "ffrostflame/bytenet@0.4.6"
BridgeNet2 = "ffrostflame/bridgenet2@1.0.0"
Warp = "imezx/warp@1.0.0"