name: Pull Request

on:
  pull_request:
    types: [opened, reopened]

jobs:
  welcome:
    name: Welcome Contributor
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: First-time Contributor Welcome
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |
            Hello @${{ github.actor }}, thank you for opening your first pull request in Satset! 🚀
            
            We appreciate your contribution. A maintainer will review your changes shortly. Please ensure you have followed our [Contributing Guidelines](CONTRIBUTING.md).
            
            Happy coding! >.<

  labeling:
    name: Auto Labeling
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Auto Labeling
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
